# path to where data is saved
data_dir:
  dsads: "~/codes_artifact_datasets/dsads/data"
  rwhar: "~/codes_artifact_datasets/rwhar"
  pamap2: "~/codes_artifact_datasets/pamap2"
  opportunity: "~/codes_artifact_datasets/opportunity/OpportunityUCIDataset/dataset/"

# relative path to where models, logs, and checkpoints will be saved
model_dir: "."